[project]
name = "prefect-init"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "toml>=0.10.2",
    "typer>=0.15.2",
    "uv>=0.6.6",
]

[project.scripts]
prefect-init = "cli:app"
